spring:
  datasource:
    hikari:
      driver-class-name: ENC(1HZt07YvcWU7NOKH5IuavzqRHwX8ZIAhUKQ6LHhYBYsXe+weWe5Ka9W9t2a40BAR)
      jdbc-url: ENC(xRfrDwUWwRUCe+Yum+XkvSOb9LWy+oMkTX7SMCPzquqZnJv8HmLZnp4lIEu4r4k1qavBkCJkgzA=)
      username: ENC(AGWQWVB3vw9SgUMHCNx1ArAyTQJC0Zsx)
      password: ENC(0yhv8bPdVB4VhsCyCha/rPKILfl8YKvhKvd+nuH8s3M=)
      maximum-pool-size: 5

  mvc:
    view:
      prefix: /html/
      suffix: .html

  devtools:
    restart:
      enabled: true
    additional-paths: src/resources/static

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )

logging:
  level:
    root: INFO

server:
  port: 18080
